"""End-to-end modem: bytes ↔ audio samples.

Signal chain
============

TX::

    payload bytes
        └─ [optional RS(24,16) outer] ──▶ bits ──▶ conv encode ──▶ interleave ──▶
           4-FSK symbols ──▶ [preamble][payload symbols repeated N times]
           ──▶ CPFSK modulate ──▶ float32 audio samples

RX::

    float32 audio samples
        ├─ magnitude demod
        ├─ preamble correlation (finds symbol timing)
        ├─ frequency-offset estimation from preamble region (compensates SSB LO drift)
        ├─ split following samples into N repeats, average magnitudes ("soft combining")
        ├─ soft LLRs -> deinterleave -> soft Viterbi -> bits
        └─ [optional RS decode] ──▶ payload bytes

No headers on the wire. Both sides must agree on ``ModemConfig``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable

import numpy as np

from weaklink.modem import fec
from weaklink.modem.interleaver import InterleaverConfig, deinterleave_soft, interleave
from weaklink.rs import BlockConfig, RSBlockCodec
from weaklink.modem.waveform import (
    BITS_PER_SYMBOL,
    NUM_TONES,
    WaveformConfig,
    bits_to_symbols,
    demodulate_soft,
    estimate_coarse_frequency_offset,
    estimate_frequency_offset,
    modulate,
    soft_bits_from_magnitudes,
)


def _generate_preamble(length: int, seed: int = 0xC05A) -> tuple[int, ...]:
    """Deterministic 4-ary preamble.

    Generated by iterating a 16-bit LFSR (Fibonacci, taps at x^16 + x^14 + x^13 + x^11)
    and taking two bits per symbol. This gives a well-distributed sequence with
    reasonable autocorrelation and no periodicity within any preamble length we
    care about (~1024). Fixed seed makes TX/RX bit-for-bit identical.

    A true Costas array would be better here, but Costas arrays of order 4 are
    only 4 symbols long; the standard weak-signal preambles that use Costas
    ideas (FT8, etc.) stitch multiple arrays together. A well-chosen PN
    sequence gets close enough for a first weakened build.
    """
    state = seed & 0xFFFF
    if state == 0:
        state = 1
    symbols: list[int] = []
    for _ in range(length):
        pair = 0
        for _ in range(2):
            bit = state & 1
            feedback = ((state >> 15) ^ (state >> 13) ^ (state >> 12) ^ (state >> 10)) & 1
            state = ((state >> 1) | (feedback << 15)) & 0xFFFF
            pair = (pair << 1) | bit
        symbols.append(pair & 0x3)
    return tuple(symbols)


@dataclass(frozen=True)
class ModemConfig:
    waveform: WaveformConfig = WaveformConfig()
    interleaver: InterleaverConfig = InterleaverConfig(rows=8, cols=32)
    preamble_length: int = 64
    """Preamble length in symbols. Longer preambles buy sync reliability at low
    SNR (~3 dB per doubling of correlation length)."""
    payload_repeats: int = 1
    """Times to send the encoded payload back-to-back. RX averages symbol
    magnitudes across repeats for ~3 dB coding gain per doubling in AWGN."""
    frequency_search_hz: float = 20.0
    """Half-range in Hz for fine freq-offset search after preamble sync. Set
    to 0 to skip fine estimation."""
    frequency_resolution_hz: float = 1.0
    coarse_frequency_search_hz: float = 0.0
    """Half-range in Hz for FFT-based coarse offset search *before* preamble
    sync. Set to e.g. 1500 to handle SSB rigs whose dial is off by up to
    ~1 kHz. Set to 0 (default) to skip; adds a few ms of runtime per decode."""
    rs_data_bytes: int | None = None
    """If set, wrap the payload in a single Reed-Solomon block of this many
    data bytes. When ``None`` the modem carries raw bytes."""
    rs_parity_bytes: int = 8
    rs_crc_enabled: bool = True

    preamble_symbols_tuple: tuple[int, ...] = field(init=False)

    def __post_init__(self) -> None:
        if self.preamble_length < 8:
            raise ValueError("preamble_length must be >= 8")
        if self.payload_repeats < 1:
            raise ValueError("payload_repeats must be >= 1")
        if self.rs_data_bytes is not None and self.rs_data_bytes < 1:
            raise ValueError("rs_data_bytes must be >= 1 when set")
        object.__setattr__(self, "preamble_symbols_tuple", _generate_preamble(self.preamble_length))

    @property
    def rs_enabled(self) -> bool:
        return self.rs_data_bytes is not None

    def rs_codec(self) -> RSBlockCodec | None:
        if not self.rs_enabled:
            return None
        assert self.rs_data_bytes is not None
        return RSBlockCodec(
            BlockConfig(
                data_bytes=self.rs_data_bytes,
                parity_bytes=self.rs_parity_bytes,
                crc_enabled=self.rs_crc_enabled,
            )
        )

    @property
    def preamble_length_symbols(self) -> int:
        return self.preamble_length


def preamble_symbols(config: ModemConfig) -> np.ndarray:
    return np.asarray(config.preamble_symbols_tuple, dtype=np.int8)


def _coded_bit_count(payload_length_bytes: int) -> int:
    return 2 * (payload_length_bytes * 8 + fec.CONSTRAINT_LENGTH - 1)


def _payload_symbol_count(payload_length_bytes: int, interleaver: InterleaverConfig) -> int:
    coded_bits = _coded_bit_count(payload_length_bytes)
    interleaved = _round_up_multiple(coded_bits, interleaver.block_size)
    padded = _round_up_multiple(interleaved, BITS_PER_SYMBOL)
    return padded // BITS_PER_SYMBOL


def encode(payload: bytes, config: ModemConfig) -> np.ndarray:
    """Encode a byte payload into a float32 audio sample stream.

    When ``config.rs_enabled`` the payload is padded to ``rs_data_bytes`` and
    wrapped in a single Reed-Solomon block before FEC + modulation.
    """
    wire_bytes = _apply_rs_encode(payload, config)
    payload_bits = _bytes_to_bits_msb(wire_bytes)
    coded = fec.encode(payload_bits)
    interleaved = interleave(coded, config.interleaver)
    payload_bit_stream = _pad_to_multiple(interleaved, BITS_PER_SYMBOL)
    single_payload_symbols = bits_to_symbols(payload_bit_stream)
    payload_symbols = np.tile(single_payload_symbols, config.payload_repeats)
    all_symbols = np.concatenate([preamble_symbols(config), payload_symbols])
    return modulate(all_symbols, config.waveform)


def _apply_rs_encode(payload: bytes, config: ModemConfig) -> bytes:
    codec = config.rs_codec()
    if codec is None:
        return payload
    if len(payload) > codec.config.data_bytes:
        raise ValueError(
            f"payload {len(payload)} bytes exceeds rs_data_bytes {codec.config.data_bytes}"
        )
    padded = payload.ljust(codec.config.data_bytes, b"\x00")
    return codec.encode(padded)


def _apply_rs_decode(wire_bytes: bytes, config: ModemConfig, payload_length_bytes: int) -> bytes:
    codec = config.rs_codec()
    if codec is None:
        return wire_bytes[:payload_length_bytes]
    decoded = codec.try_decode(wire_bytes)
    if decoded is None:
        return b"\x00" * payload_length_bytes
    return decoded[:payload_length_bytes]


def decode(samples: np.ndarray, config: ModemConfig, payload_length_bytes: int) -> bytes:
    """Decode an audio sample stream into ``payload_length_bytes`` bytes."""
    wire_length = _wire_bytes_length(config, payload_length_bytes)

    # Coarse offset first — handles big SSB LO errors before we try to find sync.
    coarse_offset_hz = 0.0
    if config.coarse_frequency_search_hz > 0.0:
        coarse_offset_hz = estimate_coarse_frequency_offset(
            np.asarray(samples, dtype=np.float64),
            config.waveform,
            search_range_hz=config.coarse_frequency_search_hz,
        )

    magnitudes = demodulate_soft(samples, config.waveform, frequency_offset_hz=coarse_offset_hz)
    if magnitudes.shape[0] == 0:
        return b"\x00" * payload_length_bytes

    sync_offset_symbols = _find_preamble(magnitudes, config)

    # Fine frequency-offset estimation using the preamble region. The fine
    # estimator searches around the coarse estimate — the two compose.
    total_offset_hz = coarse_offset_hz
    if config.frequency_search_hz > 0.0:
        samples_per_symbol = config.waveform.samples_per_symbol
        preamble_sample_start = sync_offset_symbols * samples_per_symbol
        preamble_sample_end = preamble_sample_start + config.preamble_length * samples_per_symbol
        if preamble_sample_end <= len(samples):
            preamble_slice = np.asarray(samples[preamble_sample_start:preamble_sample_end])
            total_offset_hz = estimate_frequency_offset(
                preamble_slice,
                config.waveform,
                preamble_symbols(config),
                search_range_hz=config.frequency_search_hz,
                resolution_hz=config.frequency_resolution_hz,
                prior_offset_hz=coarse_offset_hz,
            )
            magnitudes = demodulate_soft(samples, config.waveform, frequency_offset_hz=total_offset_hz)
            sync_offset_symbols = _find_preamble(magnitudes, config)

    payload_symbols_start = sync_offset_symbols + config.preamble_length
    payload_symbols_per_copy = _payload_symbol_count(wire_length, config.interleaver)
    total_needed = payload_symbols_start + payload_symbols_per_copy * config.payload_repeats
    if total_needed > magnitudes.shape[0]:
        return b"\x00" * payload_length_bytes

    # Soft combining across repeats: sum symbol magnitudes.
    combined_magnitudes = np.zeros((payload_symbols_per_copy, NUM_TONES), dtype=np.float64)
    for repeat_index in range(config.payload_repeats):
        start = payload_symbols_start + repeat_index * payload_symbols_per_copy
        combined_magnitudes += magnitudes[start : start + payload_symbols_per_copy]

    soft_bits = soft_bits_from_magnitudes(combined_magnitudes)
    coded_bits_count = _coded_bit_count(wire_length)
    deinterleaved = deinterleave_soft(soft_bits, config.interleaver, coded_bits_count)
    payload_bits = fec.decode(deinterleaved, num_output_bits=wire_length * 8)
    wire_bytes = _bits_to_bytes_msb(payload_bits)
    return _apply_rs_decode(wire_bytes, config, payload_length_bytes)


def _wire_bytes_length(config: ModemConfig, payload_length_bytes: int) -> int:
    codec = config.rs_codec()
    if codec is None:
        return payload_length_bytes
    return codec.config.block_size


def _find_preamble(magnitudes: np.ndarray, config: ModemConfig) -> int:
    """Cross-correlate the preamble tone pattern against the received magnitudes.

    Score at offset ``off`` = sum over preamble positions of
    (magnitude at correct tone) − (mean of other three tones). Broadband
    noise that lights up every tone equally scores zero; a real signal
    matching the preamble scores strongly.
    """
    preamble = preamble_symbols(config)
    preamble_length = len(preamble)
    if magnitudes.shape[0] < preamble_length:
        return 0

    tone_indices = preamble.astype(np.int64)
    positions = np.arange(preamble_length)

    max_offset = magnitudes.shape[0] - preamble_length
    scores = np.empty(max_offset + 1, dtype=np.float64)
    for offset in range(max_offset + 1):
        window = magnitudes[offset : offset + preamble_length]
        wanted = window[positions, tone_indices]
        others = (window.sum(axis=1) - wanted) / (NUM_TONES - 1)
        scores[offset] = float(np.sum(wanted - others))
    return int(np.argmax(scores))


def _bytes_to_bits_msb(data: bytes) -> bytes:
    out = bytearray(len(data) * 8)
    for byte_index, byte_value in enumerate(data):
        for bit_index in range(8):
            out[byte_index * 8 + bit_index] = (byte_value >> (7 - bit_index)) & 1
    return bytes(out)


def _bits_to_bytes_msb(bits: bytes) -> bytes:
    if len(bits) % 8 != 0:
        raise ValueError(f"bit length {len(bits)} not a multiple of 8")
    out = bytearray(len(bits) // 8)
    for index, bit in enumerate(bits):
        out[index // 8] |= (bit & 1) << (7 - (index % 8))
    return bytes(out)


def _pad_to_multiple(bits: bytes, multiple: int) -> bytes:
    if len(bits) % multiple == 0:
        return bits
    padding_count = multiple - (len(bits) % multiple)
    return bits + bytes(padding_count)


def _round_up_multiple(value: int, multiple: int) -> int:
    remainder = value % multiple
    if remainder == 0:
        return value
    return value + (multiple - remainder)
